name: ubuntu-22.04
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_ver: ["3.11", "3.13"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python_ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_ver }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./
          install -m755 ./bin/*.sh /usr/local/bin
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          pytest tests/
