name: ubuntu-22.04-pr
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      # Self-hosted env uses 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install check_utils
          pip install -r tests/requirements.txt
          pip install flake8 pytest-cov

      - name: Run tests
        run: |
          pytest --junitxml=report.xml --cov-report=term-missing:skip-covered --cov=app tests/ > coverage.txt

      - name: Pytest coverage comment
        if: ${{ always() }}
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-coverage-path: ./coverage.txt
          junitxml-path: ./report.xml
